# https://developers.cloudflare.com/workers/wrangler/configuration

# https://developers.cloudflare.com/workers/configuration/compatibility-dates
compatibility_date = "2024-10-30"

[[d1_databases]]
binding = "DB_Auth" # i.e. available in your Worker on env.DB
database_name = "Auth"
database_id = "dummy_id"
